const IMG={Grocery:'img/cat-grocery.jpg',Electronics:'img/cat-electronics.jpg',Clothing:'img/cat-clothing.jpg',Decor:'img/cat-decor.jpg',hero:'img/hero.jpg'};
const NI={'Fresh Tomatoes':'img/tomatoes.jpg','Organic Bananas':'img/bananas.jpg','Onions':'img/onions.jpg','Basmati Rice':'img/rice.jpg','Cooking Oil':'img/oil.jpg','Maggi Noodles':'img/maggi.jpg','Tata Salt':'img/salt.jpg','Amul Butter':'img/butter.jpg'};
const API=(window.SABZOMI_API||'').replace(/\/$/,'');   // '' = same server; set in index.html if the API lives elsewhere
const pimg=p=>p.image?API+p.image:(NI[p.name]||'');

const MIN=999,FREE=999,FEE=80,OF={Electronics:60,Clothing:50,Decor:50};
let P=[];
const CT=[['Grocery','🥦'],['Electronics','💻'],['Clothing','👕'],['Decor','🏺']],SUBS=['All','Fruits & Vegetables','Grains & Pulses','Dairy & Beverages','Kirana'];
let cart={},sub='All',term='',bq={};
const $=i=>document.getElementById(i),inr=n=>'₹'+n.toLocaleString('en-IN'),pf=id=>P.find(p=>p.id==id);
function toast(m){const e=$('t');e.textContent=m;e.classList.add('s');clearTimeout(toast.k);toast.k=setTimeout(()=>e.classList.remove('s'),1700)}
function T(){const it=Object.entries(cart).map(([i,q])=>({p:pf(i),q})),g=it.filter(x=>x.p.cat=='Grocery'),o=it.filter(x=>x.p.cat!='Grocery'),s=a=>a.reduce((n,x)=>n+x.p.price*x.q,0),gs=s(g),os=s(o),gf=g.length&&gs<FREE?FEE:0,of=[...new Set(o.map(x=>x.p.cat))].reduce((n,c)=>n+OF[c],0);return{g,o,gs,os,gf,of,ok:!g.length||gs>=MIN,tot:gs+os+gf+of,n:it.reduce((n,x)=>n+x.q,0)}}
const card=p=>`<div class="pc"><a class="pic" href="#product/${p.id}" aria-hidden="true" tabindex="-1">${pimg(p)?`<img src="${pimg(p)}" alt="">`:p.ic}</a><h3><a href="#product/${p.id}">${p.name}</a></h3><small>${p.unit||p.cat}</small><div class="pr">${inr(p.price)}<s>${inr(p.mrp)}</s></div><button class="btn" data-a="add" data-i="${p.id}">Add to cart</button></div>`;
const line=x=>`<div class="row"><span class="th" aria-hidden="true">${pimg(x.p)?`<img src="${pimg(x.p)}" alt="">`:x.p.ic}</span><span class="n">${x.p.name}<br><small>${inr(x.p.price)} ${x.p.unit}</small></span><span class="qty"><button data-a="q" data-d="-1" data-i="${x.p.id}" aria-label="Decrease">−</button>${x.q}<button data-a="q" data-d="1" data-i="${x.p.id}" aria-label="Increase">+</button></span><b>${inr(x.p.price*x.q)}</b></div>`;
const V={
home:()=>`<div class="hero"><div><div class="tag">Shop<b>•</b>Save<b>•</b>Refer<b>•</b>Earn</div><h1>Sabzomi</h1><p>Your one-stop online store for groceries, daily essentials, electronics, fashion and home decor.</p><a class="btn" href="#shop/Grocery">Shop now</a></div><img class="hi" src="${IMG.hero}" alt="Shopping basket filled with Aashirvaad atta, Amul, oil, Maggi and other kirana items"></div>
<div class="fs"><div><span>🛍️</span>Wide range of products</div><div><span>✅</span>Quality products</div><div><span>🔒</span>Secure payments</div><div><span>🤝</span>Earn through referrals</div></div>
<h2>Shop by category</h2><div class="cats">${CT.map(([c,i])=>`<a class="cat" href="#shop/${c}"><img src="${IMG[c]}" alt="">${c=='Decor'?'Home & Decor':c=='Clothing'?'Clothing & Fashion':c}</a>`).join('')}</div>
<h2>Top deals</h2><div class="grid">${P.slice(0,6).map(card).join('')}</div>`,
shop:c=>{c=c||'Grocery';const l=P.filter(p=>p.cat==c&&p.sub!='Package'&&(sub=='All'||p.sub==sub||c!='Grocery')&&p.name.toLowerCase().includes(term));
return`<div class="ban"><h2>${c=='Decor'?'Home & Decor':c}</h2>${c=='Grocery'?'Fresh · Healthy · Everyday':'No minimum order. Buy a single item.'}</div>${c=='Grocery'?`<div class="tabs">${SUBS.map(s=>`<button class="tb ${s==sub?'on':''}" data-a="sub" data-i="${s}">${s=='All'?'All':s}</button>`).join('')}<a class="tb" href="#packages">Grocery packages</a></div>`:''}<div class="grid">${l.length?l.map(card).join(''):'<p>No products match. Try another word or tab.</p>'}</div>`},
packages:()=>{const L=Object.entries(bq).filter(([,q])=>q>0).map(([i,q])=>({p:pf(i),q})),s=L.reduce((n,x)=>n+x.p.price*x.q,0),r=MIN-s;
return`<h2>Grocery packages</h2><p style="color:var(--mu)">Save more with value-packed monthly packages.</p><div class="grid">${P.filter(p=>p.sub=='Package').map(card).join('')}</div>
<h2>Create your own grocery basket</h2><div class="two"><div class="box">${P.filter(p=>p.cat=='Grocery'&&p.sub!='Package').slice(0,6).map(p=>{const i=p.id;return`<div class="row"><span>${p.ic}</span><span class="n">${p.name} <small>(${p.unit})</small></span><b>${inr(p.price)}</b><span class="qty"><button data-a="b" data-d="-1" data-i="${i}" aria-label="Decrease">−</button>${bq[i]||0}<button data-a="b" data-d="1" data-i="${i}" aria-label="Increase">+</button></span></div>`}).join('')}</div>
<div class="box"><div class="sum"><span>Basket subtotal</span><b>${inr(s)}</b></div><div class="bar"><i style="width:${Math.min(100,s/MIN*100)}%"></i></div>${r>0?`<div class="wr">Add ${inr(r)} more to complete your grocery order.</div>`:'<div class="ok">Minimum met. Delivery is free.</div>'}<br><button class="btn" style="width:100%" data-a="addb" ${s?'':'disabled'}>Add basket to cart</button></div></div>`},
cart:()=>{const t=T();if(!t.n)return'<div class="box" style="text-align:center;padding:40px">Your cart is empty. <a class="ok" href="#shop/Grocery">Start shopping</a></div>';
return`<h2>My cart (${t.n} items)</h2><div class="two"><div>${t.g.length?`<div class="box"><h3>Grocery order</h3>${t.g.map(line).join('')}<div class="bar"><i style="width:${Math.min(100,t.gs/MIN*100)}%"></i></div>${t.ok?'<div class="ok">Minimum met. Delivery is free.</div>':`<div class="wr">Add ${inr(MIN-t.gs)} more to complete your grocery order.</div>`}</div>`:''}${t.o.length?`<div class="box"><h3>Other items (separate order)</h3>${t.o.map(line).join('')}</div>`:''}</div>
<div class="box"><h3>Order summary</h3><div class="sum"><span>Grocery subtotal</span><span>${inr(t.gs)}</span></div><div class="sum"><span>Grocery minimum</span><span>${inr(MIN)}</span></div><div class="sum"><span>Other subtotal</span><span>${inr(t.os)}</span></div><div class="sum"><span>Delivery</span><span>${inr(t.gf+t.of)}</span></div><div class="sum"><b>Total amount</b><b>${inr(t.tot)}</b></div><div class="cp" style="margin:10px 0"><input placeholder="Have a promo code?" aria-label="Promo code"><button class="btn o" data-a="x">Apply</button></div><button class="btn" style="width:100%" data-a="pay" ${t.ok?'':'disabled'}>${t.ok?'Proceed to checkout':'Reach grocery minimum'}</button><p class="ok">Free delivery on grocery orders above ₹999</p></div></div>`},
me:s=>{s=s||'dashboard';const M={dashboard:`<div class="box"><h3>Welcome, Rahul Kumar</h3><small>Member ID: SB212345</small></div><div class="st"><div><small>Wallet balance</small><b>₹2,450</b></div><div><small>Pending commission</small><b>₹1,200</b></div><div><small>Total commission</small><b>₹3,650</b></div><div><small>Total downline</small><b>48</b></div></div><div class="box"><b>Your referral link</b><div class="cp" style="margin-top:8px"><input readonly value="https://sabzomi.com/register?ref=SB212345" aria-label="Referral link"><button class="btn" data-a="copy">Copy</button></div></div><div class="box"><b>Recent orders</b><table><tr><th>Order</th><th>Date</th><th>Amount</th><th>Status</th></tr><tr><td>#ORD1048</td><td>12 Apr</td><td>₹1,240</td><td><span class="pill">Delivered</span></td></tr><tr><td>#ORD1042</td><td>10 Apr</td><td>₹860</td><td><span class="pill p">Shipped</span></td></tr></table></div>`,
network:`<div class="st"><div><small>Direct referrals</small><b>12</b></div><div><small>Level 2</small><b>24</b></div><div><small>Level 3</small><b>18</b></div><div><small>Total downline</small><b>48</b></div></div><div class="box tree"><div class="av">You</div><small>SB212345</small><div class="kids">${['Amit','Neha','Rohit'].map((n,i)=>`<div><div class="av">${n[0]}</div>${n}<small>SB20${i+1}</small></div>`).join('')}</div><p style="color:var(--mu)">You earn commission when your downline shops on Sabzomi. Amounts depend on eligible orders.</p></div>`,
wallet:`<div class="st"><div><small>Total balance</small><b>₹2,450</b></div><div><small>Available</small><b>₹1,800</b></div><div><small>Pending</small><b>₹650</b></div></div><div style="display:flex;gap:10px;margin-bottom:14px"><button class="btn" data-a="x">Add money</button><button class="btn o" data-a="x">Withdraw</button></div><div class="box"><table><tr><th>Date</th><th>Type</th><th>Amount</th><th>Status</th></tr><tr><td>12 Apr</td><td>Commission</td><td>+₹350</td><td><span class="pill">Completed</span></td></tr><tr><td>10 Apr</td><td>Order payment</td><td>−₹1,250</td><td><span class="pill">Completed</span></td></tr><tr><td>05 Apr</td><td>Withdrawal</td><td>−₹1,000</td><td><span class="pill p">Pending</span></td></tr></table></div>`,
admin:`<div class="st"><div><small>Total users</small><b>1,248</b></div><div><small>Total orders</small><b>892</b></div><div><small>Total sales</small><b>₹4,85,320</b></div><div><small>Commission</small><b>₹68,450</b></div></div><div class="box"><b>Sales overview (last 7 days)</b><svg viewBox="0 0 300 90" width="100%" role="img" aria-label="Sales trend"><polyline fill="none" stroke="var(--g)" stroke-width="3" points="0,70 50,50 100,60 150,30 200,45 250,20 300,35"/></svg></div><div class="box"><b>Recent orders</b><table><tr><th>Order</th><th>User</th><th>Amount</th><th>Status</th></tr><tr><td>#ORD1048</td><td>Rohan S.</td><td>₹1,240</td><td><span class="pill">Delivered</span></td></tr><tr><td>#ORD1039</td><td>Amit K.</td><td>₹520</td><td><span class="pill p">Confirmed</span></td></tr></table></div>`};
const N=[['dashboard','Dashboard'],['network','My network'],['wallet','Wallet'],['admin','Admin panel']];
return`<div class="pn"><div class="sd"><div class="logo">Sabz<i>o</i>mi</div>${N.map(([k,l])=>`<a href="#me/${k}" class="${k==s?'on':''}">${l}</a>`).join('')}</div><div>${M[s]}<p style="color:var(--mu);font-size:12px">Sample data for design preview only.</p></div></div>`}};
function render(){const[r,a]=location.hash.slice(1).split('/');const R=V[r]?r:'home';const my=++RN;Promise.resolve().then(()=>V[R](a)).then(x=>{if(my==RN)$('app').innerHTML=x}).catch(e=>{if(my==RN)$('app').innerHTML=`<div class="box"><b>${esc(e.message)}</b><p><a class="ok" href="#login">Login again</a></p></div>`});
const L=[['home','Home','🏠'],['shop/Grocery','Grocery','🥦'],['shop/Electronics','Electronics','💻'],['shop/Clothing','Clothing','👕'],['shop/Decor','Home & Decor','🏺'],['packages','Packages','🧺'],['me/dashboard','Account','👤']];
const on=l=>(l.split('/')[0]==R&&(R!='shop'||l.endsWith(a||'Grocery')))?'on':'';
$('nav').innerHTML=L.map(l=>`<a href="#${l[0]}" class="${on(l[0])}">${l[1]}</a>`).join('');
$('mb').innerHTML=[L[0],L[1],L[5],['cart','Cart','🛒'],L[6]].map(l=>`<a href="#${l[0]}" class="${on(l[0])}"><span>${l[2]}</span>${l[1]}</a>`).join('');$('cnt').textContent=T().n;hdr()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-a]');if(!b)return;const a=b.dataset.a,i=b.dataset.i,d=+b.dataset.d;
if(a=='add'){cart[i]=(cart[i]||0)+1;toast('Added to cart');$('cnt').textContent=T().n;return}
if(a=='q'){cart[i]+=d;if(cart[i]<=0)delete cart[i]}
if(a=='b'){bq[i]=Math.max(0,(bq[i]||0)+d)}
if(a=='sub')sub=i;
if(a=='addb'){for(const k in bq)if(bq[k])cart[k]=(cart[k]||0)+bq[k];toast('Basket added to cart');location.hash='cart'}
if(a=='pay'){location.hash='checkout';return}
if(a=='x')toast('Available in the next build');
if(a=='copy')toast('Referral link copied');
render()});
$('q').oninput=e=>{term=e.target.value.toLowerCase().trim();if(!location.hash.startsWith('#shop'))location.hash='shop/Grocery';else render()};

/* ===== Live API layer ===== */
let TOK=null,USER=null,RN=0,NEXT='',lm=new URLSearchParams(location.search).get('ref')?'reg':'login';
const REF=(new URLSearchParams(location.search).get('ref')||'').toUpperCase();
const CK={name:'',phone:'',line1:'',pincode:'411001',method:'wallet',coupon:''};
try{TOK=localStorage.getItem('sz_t')}catch(e){}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=p=>'₹'+(p/100).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
const dt=t=>new Date(t*1000).toLocaleDateString('en-IN');
const tbl=(h,r)=>`<table><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr>${r.map(c=>`<tr>${c.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${h.length}">Nothing here yet.</td></tr>`}</table>`;
const pill=s=>`<span class="pill ${/pending|processing|approved|requested|created/.test(s)?'p':''}">${esc(s)}</span>`;
const stats=a=>`<div class="st">${a.map(([l,v])=>`<div><small>${l}</small><b>${v}</b></div>`).join('')}</div>`;
const items=()=>Object.entries(cart).map(([i,q])=>({product_id:+i,qty:q}));
async function api(path,o={}){const r=await fetch(API+'/api'+path,{method:o.m||'GET',headers:{'Content-Type':'application/json',...(TOK?{Authorization:'Bearer '+TOK}:{})},body:o.b?JSON.stringify(o.b):undefined});let d={};try{d=await r.json()}catch(e){}if(!r.ok){if(r.status==401&&TOK){TOK=USER=null;try{localStorage.removeItem('sz_t')}catch(e){}}const e=new Error(d.error||'Request failed');e.data=d;throw e}return d}
function setAuth(d){TOK=d.token;USER=d.user;try{localStorage.setItem('sz_t',TOK)}catch(e){}}
function logout(){TOK=USER=null;try{localStorage.removeItem('sz_t')}catch(e){}location.hash='home';toast('Logged out')}
function hdr(){const a=$('acct');if(a)a.textContent=USER?USER.name.split(' ')[0]+' · Logout':'Login / Register'}
async function loadProducts(){const d=await api('/products?limit=100'),ic={Grocery:'🛒',Electronics:'🎧',Clothing:'👕',Decor:'🏺'};P=d.products.map(p=>({id:p.id,name:p.name,unit:p.unit,cat:p.category,sub:p.sub,price:p.price_paise/100,mrp:p.mrp_paise/100,image:p.image,ic:p.sub=='Package'?'🧺':ic[p.category]||'🛍️'}))}
async function boot(){if(RESET&&location.hash!='#reset')location.hash='reset';try{await loadProducts()}catch(e){toast('Could not load products')}if(TOK){try{USER=(await api('/me')).user}catch(e){}}render()}
$('acct').addEventListener('click',e=>{if(USER){e.preventDefault();logout()}});

V.login=()=>{const r=lm=='reg';return`<div class="box" style="max-width:420px;margin:auto"><div class="tabs"><button class="tb ${r?'':'on'}" data-z="lm" data-i="login">Login</button><button class="tb ${r?'on':''}" data-z="lm" data-i="reg">Register</button></div><form class="fm" data-f="${lm}">${r?'<input name="name" placeholder="Full name" required><input name="phone" placeholder="Mobile (10 digits)" required>':''}<input name="email" type="email" placeholder="Email" required><input name="password" type="password" placeholder="Password (min 8 characters)" required minlength="8">${r?`<input name="referral_code" placeholder="Referral code (optional)" value="${esc(REF)}"><label style="font-size:13px"><input type="checkbox" required> I agree to the <a class="ok" href="#page/terms" target="_blank">Terms</a>, <a class="ok" href="#page/privacy" target="_blank">Privacy Policy</a> and <a class="ok" href="#page/earnings" target="_blank">Earnings Disclaimer</a></label>`:''}<button class="btn">${r?'Create account':'Login'}</button><small class="e" id="ferr"></small></form></div>`};

V.checkout=async()=>{if(!TOK){NEXT='checkout';return V.login()}if(!T().n)return V.cart();
 let q=null,err='';try{q=await api('/checkout/quote',{m:'POST',b:{items:items(),address:{pincode:CK.pincode},coupon:CK.coupon,payment_method:CK.method}})}catch(e){err=e.message}
 const w=await api('/wallet');
 return`<h2>Checkout</h2><div class="two"><form class="box fm" data-f="checkout"><h3>Delivery address</h3><input name="name" placeholder="Full name" value="${esc(CK.name||USER.name)}" required><input name="phone" placeholder="Mobile" value="${esc(CK.phone)}" required><input name="line1" placeholder="Flat / street / area" value="${esc(CK.line1)}" required><input name="pincode" placeholder="PIN code" value="${esc(CK.pincode)}" required><input name="coupon" placeholder="Promo code" value="${esc(CK.coupon)}"><h3>Payment</h3><label><input type="radio" name="method" value="wallet" ${CK.method=='wallet'?'checked':''}> Sabzomi wallet (${money(w.available_paise)})</label><label><input type="radio" name="method" value="gateway" ${CK.method=='gateway'?'checked':''}> Online payment (UPI / Card / Net banking)</label><button type="button" class="btn o" data-z="ckupd">Update totals</button><button class="btn" ${q?'':'disabled'}>Place order</button><small class="e" id="ferr">${esc(err)}</small></form>
 <div class="box"><h3>Order summary</h3>${q?q.groups.map(g=>`<p><b>${g.type=='grocery'?'Grocery order':'Other items (separate order)'}</b></p><div class="sum"><span>Subtotal</span><span>${money(g.subtotal_paise)}</span></div>${g.discount_paise?`<div class="sum"><span>Discount</span><span>−${money(g.discount_paise)}</span></div>`:''}<div class="sum"><span>Delivery</span><span>${g.delivery_paise?money(g.delivery_paise):'Free'}</span></div>`).join('')+`<hr><div class="sum"><b>Grand total</b><b>${money(q.grand_total_paise)}</b></div>`:`<div class="wr">${esc(err)}</div>`}</div></div>`};

V.orders=async()=>{if(!TOK){NEXT='orders';return V.login()}const d=await api('/orders');
 return`<h2>My orders</h2><div class="box">${tbl(['Order','Date','Total','Payment','Status',''],d.orders.map(o=>[o.order_no,dt(o.created_at),money(o.total_paise),pill(o.payment_status),pill(o.status),(o.status=='pending'&&o.payment_method=='gateway'&&o.payment_status=='pending'?`<button class="btn" data-z="paynow" data-i="${o.order_no}">Pay now</button> `:'')+(['pending','confirmed'].includes(o.status)?`<button class="btn o" data-z="cancel" data-i="${o.order_no}">Cancel</button>`:o.status=='delivered'?`<button class="btn o" data-z="ret" data-i="${o.order_no}">Return</button>`:'')]))}</div>`};

const node=n=>`<div><div class="av">${esc(n.name[0])}</div>${esc(n.name)}<small>${n.account_id}</small>${n.children.length?`<div class="kids">${n.children.map(node).join('')}</div>`:''}</div>`;
V.me=async s=>{if(!TOK){NEXT='me/'+(s||'dashboard');return V.login()}s=s||'dashboard';if(!USER)USER=(await api('/me')).user;
 const N=[['#me/dashboard','Dashboard','dashboard'],['#me/network','My network','network'],['#me/wallet','Wallet','wallet'],['#orders','My orders',''],['#me/notifications','Notifications','notifications'],['#me/support','Support','support'],['#me/profile','Profile','profile']].concat(USER.role=='admin'?[['#me/admin','Admin panel','admin'],['#me/aorders','Orders','aorders'],['#me/ausers','Users','ausers'],['#me/areturns','Returns','areturns'],['#me/adelivery','Delivery & coupons','adelivery'],['#me/commission','Commission settings','commission'],['#me/products','Products','products']]:[]);let h='';
 if(s=='dashboard'){const d=await api('/dashboard'),w=d.wallet,l=location.origin+'/?ref='+d.user.referral_code;
  h=`<div class="box"><h3>Welcome, ${esc(d.user.name)}</h3><small>Account ID: ${d.user.account_id}</small></div>${stats([['Available balance',money(w.available_paise)],['Pending commission',money(w.pending_commission_paise)],['Total commission',money(w.total_commissions_paise)],['Total downline',d.downline]])}<div class="box"><b>Your referral code: ${d.user.referral_code}</b><div class="cp" style="margin-top:8px"><input readonly value="${esc(l)}" aria-label="Referral link"><button class="btn" data-z="copy" data-i="${esc(l)}">Copy</button><a class="btn o" target="_blank" rel="noopener" href="https://wa.me/?text=${encodeURIComponent('Shop on Sabzomi and earn through referrals: '+l)}">WhatsApp</a></div></div><div class="box"><b>Recent orders</b>${tbl(['Order','Amount','Status'],d.recent_orders.map(o=>[o.order_no,money(o.total_paise),pill(o.status)]))}</div>`}
 else if(s=='network'){const [st,t]=await Promise.all([api('/referrals/stats'),api('/referrals/tree?depth=3')]);
  h=stats([['Direct referrals',st.direct],['Total downline',st.total_downline],['Active downline',st.active_downline]])+`<div class="box tree">${node(t)}<p style="color:var(--mu)">You earn commission when your downline shops on Sabzomi. Amounts depend on eligible orders and are not guaranteed.</p></div>`}
 else if(s=='wallet'){const [w,tx,wd,cm,me]=await Promise.all([api('/wallet'),api('/wallet/transactions?limit=10'),api('/withdrawals'),api('/commissions?limit=10'),api('/me')]);
  h=stats([['Available',money(w.available_paise)],['Pending commission',money(w.pending_commission_paise)],['In withdrawal',money(w.withdrawals_in_process_paise)],['Total withdrawn',money(w.total_withdrawn_paise)]])+`<div class="box"><b>Add money</b><form class="cp" data-f="topup"><input name="amount" type="number" min="100" placeholder="Amount in ₹" required aria-label="Amount"><button class="btn">Add money</button></form><br><b>Payout details</b> <small>${me.payout?`Saved: ${me.payout.upi?'UPI '+esc(me.payout.upi)+' ':''}${me.payout.bank?'Bank '+esc(me.payout.bank.account)+' ('+esc(me.payout.bank.ifsc)+')':''}`:'none saved yet'}</small><form class="cp" data-f="payout" style="margin:8px 0"><input name="upi" placeholder="UPI ID, e.g. name@okaxis" aria-label="UPI ID"><button class="btn o">Save UPI</button></form><form class="fm" data-f="bank" style="margin-bottom:12px"><input name="holder" placeholder="Account holder name" required><input name="account" placeholder="Account number" required><input name="ifsc" placeholder="IFSC (e.g. HDFC0001234)" required><input name="bank_name" placeholder="Bank name"><button class="btn o">Save bank account</button></form><b>Withdraw</b><form class="cp" data-f="wd" style="margin-top:8px"><select name="method" aria-label="Method" style="padding:10px;border:1px solid var(--ln);border-radius:8px;background:var(--bg);color:var(--ink)"><option value="upi">UPI</option><option value="bank">Bank</option></select><input name="amount" type="number" placeholder="Amount in ₹" required aria-label="Withdraw amount"><button class="btn">Withdraw</button></form><small class="e" id="ferr"></small></div><div class="box"><b>Transactions</b>${tbl(['Date','Type','Amount'],tx.transactions.map(t=>[dt(t.created_at),esc(t.type.replace(/_/g,' ')),(t.direction=='credit'?'+':'−')+money(t.amount_paise)]))}</div><div class="box"><b>Commissions</b>${tbl(['Order','Level','Amount','Status'],cm.commissions.map(c=>[c.order_no,c.level,money(c.amount_paise),pill(c.status)]))}</div><div class="box"><b>Withdrawals</b>${tbl(['Date','Amount','Status'],wd.withdrawals.map(x=>[dt(x.created_at),money(x.amount_paise),pill(x.status)]))}</div>`}
 else if(s=='notifications'){const d=await api('/notifications');await api('/notifications/read',{m:'POST'});h=`<div class="box"><b>Notifications</b>${tbl(['Date','Update'],d.notifications.map(n=>[dt(n.created_at),`<b>${esc(n.title)}</b> ${esc(n.body||'')}${n.is_read?'':' <span class="pill p">new</span>'}`]))}</div>`}
 else if(s=='support'){const d=await api('/tickets');h=`<div class="box"><b>New support request</b><form class="fm" data-f="ticket"><input name="subject" placeholder="Subject" required maxlength="120"><textarea name="message" placeholder="Describe your issue" required rows="3" style="padding:10px;border:1px solid var(--ln);border-radius:8px;background:var(--bg);color:var(--ink);font:inherit"></textarea><button class="btn">Send</button><small class="e" id="ferr"></small></form></div><div class="box"><b>Your tickets</b>${tbl(['Subject','Status','Updated',''],d.tickets.map(t=>[esc(t.subject),pill(t.status),dt(t.updated_at),`<a class="ok" href="#me/ticket-${t.id}">Open</a>`]))}</div>`}
 else if(s.startsWith('ticket-')){const id=s.slice(7),d=await api('/tickets/'+id);h=`<div class="box"><h3>${esc(d.ticket.subject)}</h3>${pill(d.ticket.status)} <a class="ok" href="#me/support">← All tickets</a>${d.messages.map(m=>`<div class="box" style="margin-top:10px;${m.is_admin?'background:var(--tn)':''}"><small>${m.is_admin?'Sabzomi support':'Customer'} · ${dt(m.created_at)}</small><p>${esc(m.body)}</p></div>`).join('')}<form class="fm" data-f="reply" data-t="${id}"><input name="message" placeholder="Write a reply" required><button class="btn">Reply</button>${USER.role=='admin'?`<button type="button" class="btn o" data-z="tclose" data-i="${id}">Close ticket</button>`:''}</form></div>`}
 else if(s=='profile'){h=`<div class="box"><b>Profile</b><p>Account ID: ${USER.account_id} · ${esc(USER.email)} · ${esc(USER.phone)}</p><form class="fm" data-f="profile"><input name="name" value="${esc(USER.name)}" required><button class="btn">Save name</button></form></div><div class="box"><b>Change password</b><form class="fm" data-f="pw"><input name="current" type="password" placeholder="Current password" required><input name="new" type="password" placeholder="New password (min 8)" minlength="8" required><button class="btn">Update password</button><small class="e" id="ferr"></small></form></div>`}
 else if(['aorders','ausers','areturns','adelivery'].includes(s)&&USER.role=='admin'){h=await ADMIN_SECTIONS(s)}
 else if(s=='commission'&&USER.role=='admin'){const c=await api('/admin/settings');h=`<div class="box"><b>Commission settings</b> <small>(internal admin only)</small><form class="fm" data-f="cfg"><label>MLM pool, % of net margin <input name="pool" type="number" step="0.01" value="${c.mlm_pool_bp/100}" required></label><label>Level % of pool (level 1 = direct referrer), comma separated <input name="levels" value="${c.level_bp.map(x=>x/100).join(',')}" required></label><label>Grocery minimum ₹ <input name="gmin" type="number" value="${c.grocery_min_paise/100}" required></label><label>Free delivery from ₹ <input name="free" type="number" value="${c.free_delivery_paise/100}" required></label><label>Grocery delivery fee ₹ <input name="fee" type="number" value="${c.grocery_fee_paise/100}" required></label><label>Commission release period (days) <input name="days" type="number" value="${c.release_days}" required></label><label>Preview with net margin ₹ <input name="margin" type="number" value="200"></label><div style="display:flex;gap:10px"><button type="button" class="btn o" data-z="cprev">Preview</button><button class="btn">Save settings</button></div><small class="e" id="ferr"></small></form><div id="prev" class="box" style="margin-top:12px">Click Preview to see the commission structure before saving.</div></div>`}
 else if(s=='products'&&USER.role=='admin'){const d=await api('/admin/products');h=`<div class="box"><b>Add product</b><form class="fm" data-f="newprod"><input name="sku" placeholder="SKU" required><input name="name" placeholder="Name" required><select name="category" style="padding:10px;border:1px solid var(--ln);border-radius:8px;background:var(--bg);color:var(--ink)"><option>Grocery</option><option>Electronics</option><option>Clothing</option><option>Decor</option></select><input name="sub" placeholder="Sub-category (optional)"><input name="unit" placeholder="Unit (e.g. 1 kg)"><input name="price" type="number" step="0.01" placeholder="Selling price ₹" required><input name="mrp" type="number" step="0.01" placeholder="MRP ₹" required><input name="cost" type="number" step="0.01" placeholder="Purchase cost ₹ (internal)" required><input name="other" type="number" step="0.01" placeholder="Other costs ₹ (internal)" value="0"><input name="tax" type="number" step="0.01" placeholder="Tax % included in price" value="0"><input name="stock" type="number" placeholder="Stock" required><button class="btn">Add product</button><small class="e" id="ferr"></small></form></div><div class="box"><b>Products</b> <small>INTERNAL ADMIN ONLY: margin and MLM pool per unit</small>${tbl(['Product','Price','Stock','Net margin','MLM pool','Status',''],d.products.map(p=>[esc(p.name),money(p.price_paise),p.stock,money(p.internal_admin_only.net_margin_paise),money(p.internal_admin_only.mlm_pool_paise),p.active?pill('active'):pill('hidden'),`<button class="btn o" data-z="pimg" data-i="${p.id}">Photo</button> <button class="btn o" data-z="stock" data-i="${p.id}">Stock</button> <button class="btn o" data-z="toggle" data-i="${p.id}" data-s="${p.active?0:1}">${p.active?'Hide':'Show'}</button>`]))}</div>`}
 else if(s=='admin'&&USER.role=='admin'){const [d,o,w,fl,tk]=await Promise.all([api('/admin/dashboard'),api('/admin/orders?limit=8'),api('/admin/withdrawals'),api('/admin/risk-flags'),api('/admin/tickets')]);
  const nx={pending:[['approved','Approve'],['rejected','Reject']],approved:[['processing','Processing']],processing:[['paid','Mark paid'],['failed','Failed']]};
  h=stats([['Users',d.total_users],['Orders',d.total_orders],['Sales',money(d.total_sales_paise)],['Commission',money(d.total_commission_paise)],['Open risk flags',d.open_risk_flags]])+`<div class="box"><button class="btn" data-z="release">Release due commissions</button> <button class="btn o" data-z="maint">Run maintenance</button> <b style="margin-left:10px">Export CSV:</b> ${['orders','users','commissions','ledger','withdrawals'].map(k=>`<button class="btn o" data-z="export" data-i="${k}">${k}</button>`).join(' ')}</div><div class="box"><b>Withdrawal requests</b>${tbl(['ID','User','Amount','Status','Action'],w.withdrawals.filter(x=>nx[x.status]).map(x=>[x.id,x.account_id,money(x.amount_paise),pill(x.status),nx[x.status].map(([k,l])=>`<button class="btn o" data-z="wd" data-i="${x.id}" data-s="${k}">${l}</button>`).join(' ')]))}</div><div class="box"><b>Recent orders</b>${tbl(['Order','Total','Status'],o.orders.map(x=>[x.order_no,money(x.total_paise),pill(x.status)]))}</div><div class="box"><b>Risk flags</b>${tbl(['User','Type','Detail',''],fl.flags.filter(x=>x.status=='open').map(x=>[x.user_id||'-',esc(x.kind),esc(x.detail),`<button class="btn o" data-z="flag" data-i="${x.id}">Mark reviewed</button>`]))}</div><div class="box"><b>Open support tickets</b>${tbl(['User','Subject','Status',''],tk.tickets.map(x=>[x.account_id,esc(x.subject),pill(x.status),`<a class="ok" href="#me/ticket-${x.id}">Open</a>`]))}</div>`}
 return`<div class="pn"><div class="sd"><div class="logo">Sabz<i>o</i>mi</div>${N.map(([u,l,k])=>`<a href="${u}" class="${k==s?'on':''}">${l}</a>`).join('')}</div><div>${h}</div></div>`};


V.product=async id=>{const p=P.find(x=>x.id==id);if(!p)return'<div class="box">Product not found. <a class="ok" href="#shop/Grocery">Back to shop</a></div>';
 const sim=P.filter(x=>x.cat==p.cat&&x.id!=p.id&&x.sub!='Package').slice(0,4),off=p.mrp>p.price?Math.round((1-p.price/p.mrp)*100):0;let stock=0;try{stock=(await api('/products/'+p.id)).stock}catch(e){}
 return`<p><a class="ok" href="#shop/${p.cat}">← ${p.cat=='Decor'?'Home & Decor':p.cat}</a></p><div class="two"><div class="box"><div class="pic" style="height:300px;font-size:120px">${pimg(p)?`<img src="${pimg(p)}" alt="${esc(p.name)}">`:p.ic}</div></div><div class="box"><h2 style="margin-top:0">${esc(p.name)}</h2><small>${esc(p.unit||p.cat)}</small><div class="pr" style="font-size:26px;margin:10px 0">${inr(p.price)}<s>${inr(p.mrp)}</s> ${off?`<span class="pill">${off}% off</span>`:''}</div><p class="${stock>0?'ok':'wr'}">${stock>0?(stock<10?'Only '+stock+' left':'In stock'):'Out of stock'}</p><div style="display:flex;gap:10px;flex-wrap:wrap"><button class="btn" data-a="add" data-i="${p.id}" ${stock>0?'':'disabled'}>Add to cart</button><a class="btn o" href="#cart" data-a="add" data-i="${p.id}">Buy now</a></div><p style="color:var(--mu)">${p.cat=='Grocery'?'Grocery orders have a minimum of ₹999. Delivery is free from ₹999.':'No minimum order. Buy a single item.'} Secure payments · Easy returns.</p></div></div><h2>Similar products</h2><div class="grid">${sim.map(card).join('')||'<p>No similar products yet.</p>'}</div>`};

function loadRzp(){return new Promise((ok,no)=>{if(window.Razorpay)return ok();const s=document.createElement('script');s.src='https://checkout.razorpay.com/v1/checkout.js';s.onload=ok;s.onerror=()=>no(new Error('Could not load the payment window'));document.head.appendChild(s)})}
async function payNow(p){if(p.provider!='razorpay')return devPay(p.gateway_order_id);
 try{await loadRzp()}catch(e){toast(e.message);return false}
 return new Promise(res=>{new Razorpay({key:p.key_id,order_id:p.gateway_order_id,amount:p.amount_paise,currency:'INR',name:'Sabzomi',description:'Shop · Save · Refer · Earn',prefill:{name:USER.name,email:USER.email,contact:USER.phone},theme:{color:'#1b6b3a'},
  handler:async x=>{try{await api('/payments/verify',{m:'POST',b:{gateway_order_id:p.gateway_order_id,payment_id:x.razorpay_payment_id,signature:x.razorpay_signature}});res(true)}catch(e){toast(e.message);res(false)}},modal:{ondismiss:()=>res(false)}}).open()})}


/* ===== Forgot / reset password, legal pages ===== */
const RESET=new URLSearchParams(location.search).get('reset')||'';let ST_F='',UQ='';
const _login=V.login;
V.login=()=>{if(lm=='forgot')return`<div class="box" style="max-width:420px;margin:auto"><h3>Reset password</h3><p style="color:var(--mu)">Enter your account email and we will send a reset link.</p><form class="fm" data-f="forgot"><input name="email" type="email" placeholder="Email" required><button class="btn">Send reset link</button><small class="e" id="ferr"></small></form><p><button class="tb" data-z="lm" data-i="login">← Back to login</button></p></div>`;
 return _login().replace('</form></div>','</form><p style="text-align:center"><button type="button" class="tb" data-z="lm" data-i="forgot">Forgot password?</button></p></div>')};
V.reset=()=>`<div class="box" style="max-width:420px;margin:auto"><h3>Choose a new password</h3><form class="fm" data-f="reset"><input name="new" type="password" placeholder="New password (min 8 characters)" minlength="8" required><button class="btn">Update password</button><small class="e" id="ferr"></small></form></div>`;
const LEGAL={
terms:['Terms of Use',['By using Sabzomi you agree to these terms. Provide accurate information, keep your password private and use the platform lawfully.','Prices, offers and availability can change without notice. An order is accepted when Sabzomi confirms it.','Grocery orders have a minimum value and delivery charges as shown at checkout. Electronics, clothing and home & decor can be bought as single items.','Accounts that misuse the referral programme (fake or duplicate accounts, self-referral, order manipulation) can be suspended, and unpaid earnings can be withheld or reversed.']],
privacy:['Privacy Policy',['We collect your name, email, mobile number, delivery addresses, order, wallet and referral-network data to run your account, deliver orders, process payments, prevent fraud and provide support.','Card and UPI details are handled by our payment partner and are not stored by Sabzomi. Bank and UPI details you save for withdrawals are stored encrypted and shown masked.','We do not sell your personal data. We share only what is needed with delivery and payment partners, or when the law requires it.','To correct or delete your data, raise a request from Account → Support.']],
refunds:['Refunds & Returns',['Orders can be cancelled before dispatch. Paid cancelled orders are refunded to your Sabzomi wallet.','After delivery you can request a return or refund from My orders within 7 days. Approved refunds are credited to your Sabzomi wallet.','Referral commission earned on an order is reversed if that order is cancelled, returned or refunded.']],
earnings:['Earnings Disclaimer',['Referral earnings are not guaranteed. Commission is paid only on genuine product purchases made by people in your network; joining or referring alone earns nothing.','Commission starts as pending and becomes available after a release period. It is reversed if the related order is cancelled, returned or refunded.','Commission rates and rules may change for future orders. Amounts shown as examples are illustrations only and are not a promise of income.']]};
V.page=async s=>{if(s=='contact'){let e='';try{e=(await api('/config')).support_email}catch(x){}return`<div class="box" style="max-width:720px;margin:auto"><h2>Contact us</h2><p>${e?`Email: <a class="ok" href="mailto:${esc(e)}">${esc(e)}</a><br>`:''}Logged-in customers can raise a request any time from <a class="ok" href="#me/support">Account → Support</a>.</p></div>`}
 const l=LEGAL[s];if(!l)return'<div class="box">Page not found.</div>';return`<div class="box" style="max-width:720px;margin:auto"><h2>${l[0]}</h2>${l[1].map(t=>`<p>${t}</p>`).join('')}<p style="color:var(--mu);font-size:12px">Last updated: ${new Date().getFullYear()}</p></div>`};

/* ===== Admin: orders, users, returns, delivery & coupons ===== */
const ADMIN_SECTIONS=async s=>{let h='';
 if(s=='aorders'){const d=await api('/admin/orders?limit=60'+(ST_F?'&status='+ST_F:''));const nx={confirmed:['processing'],processing:['packed'],packed:['shipped'],shipped:['out_for_delivery'],out_for_delivery:['delivered']},cn=['pending','confirmed','processing','packed'];
  h=`<div class="box"><b>Orders</b><div class="tabs" style="margin-top:8px">${['','pending','confirmed','processing','packed','shipped','out_for_delivery','delivered','cancelled','refunded'].map(x=>`<button class="tb ${x==ST_F?'on':''}" data-z="ofilter" data-i="${x}">${x?x.replace(/_/g,' '):'All'}</button>`).join('')}</div>${tbl(['Order','Date','Type','Total','Payment','Status','Action'],d.orders.map(o=>[o.order_no,dt(o.created_at),o.group_type,money(o.total_paise),pill(o.payment_status),pill(o.status),(nx[o.status]||[]).map(k=>`<button class="btn" data-z="ost" data-i="${o.order_no}" data-s="${k}">→ ${k.replace(/_/g,' ')}</button>`).join(' ')+(cn.includes(o.status)?` <button class="btn o" data-z="ost" data-i="${o.order_no}" data-s="cancelled">Cancel</button>`:'')+(o.status=='delivered'?` <button class="btn o" data-z="ost" data-i="${o.order_no}" data-s="refunded">Refund</button>`:'')]))}</div>`}
 else if(s=='ausers'){const d=await api('/admin/users?limit=50&q='+encodeURIComponent(UQ));
  h=`<div class="box"><form class="cp" data-f="usearch"><input name="q" value="${esc(UQ)}" placeholder="Search name, email, account ID, referral code" aria-label="Search users"><button class="btn">Search</button></form>${tbl(['ID','Name','Email','Status','Sponsor','Joined','Actions'],d.users.map(u=>[u.account_id,esc(u.name),esc(u.email),pill(u.status),u.sponsor_id||'-',dt(u.created_at),u.role=='admin'?'admin':`<button class="btn o" data-z="ustat" data-i="${u.id}" data-s="${u.status=='active'?'suspended':'active'}">${u.status=='active'?'Suspend':'Activate'}</button> <button class="btn o" data-z="uwal" data-i="${u.id}">Wallet</button> <button class="btn o" data-z="uspon" data-i="${u.id}">Sponsor</button>`]))}</div>`}
 else if(s=='areturns'){const d=await api('/admin/returns');
  h=`<div class="box"><b>Return / refund requests</b>${tbl(['Order','Type','Reason','Status','Action'],d.returns.map(r=>[r.order_no,r.kind,esc(r.reason||''),pill(r.status),['requested','approved'].includes(r.status)?`<button class="btn" data-z="ret2" data-i="${r.id}" data-s="refund">Refund</button> <button class="btn o" data-z="ret2" data-i="${r.id}" data-s="approve">Approve</button> <button class="btn o" data-z="ret2" data-i="${r.id}" data-s="reject">Reject</button>`:'']))}</div>`}
 else if(s=='adelivery'){const [p,c]=await Promise.all([api('/admin/pincodes'),api('/admin/coupons')]);
  h=`<div class="box"><b>Delivery PIN codes</b> <small>Customers can only order to PIN codes listed here.</small><form class="cp" data-f="pin" style="margin:8px 0"><input name="pin" placeholder="6-digit PIN code" pattern="[0-9]{6}" required><input name="fee" type="number" step="0.01" placeholder="Extra delivery fee ₹" value="0"><button class="btn">Add / update</button></form><small class="e" id="ferr"></small>${tbl(['PIN','Extra fee','Status',''],p.pincodes.map(x=>[x.pincode,money(x.fee_paise),x.active?pill('active'):pill('off'),`<button class="btn o" data-z="pintog" data-i="${x.pincode}" data-s="${x.active?0:1}" data-fee="${x.fee_paise}">${x.active?'Disable':'Enable'}</button>`]))}</div>
  <div class="box"><b>Coupons</b><form class="fm" data-f="coupon"><input name="code" placeholder="Code, e.g. WELCOME10" required><select name="kind" style="padding:10px;border:1px solid var(--ln);border-radius:8px;background:var(--bg);color:var(--ink)"><option value="percent">Percent off</option><option value="flat">Flat ₹ off</option></select><input name="value" type="number" step="0.01" placeholder="Value (% or ₹)" required><input name="min" type="number" step="0.01" placeholder="Minimum order ₹" value="0"><input name="max" type="number" step="0.01" placeholder="Max discount ₹ (0 = none)" value="0"><select name="applies" style="padding:10px;border:1px solid var(--ln);border-radius:8px;background:var(--bg);color:var(--ink)"><option value="all">All items</option><option value="grocery">Grocery only</option><option value="other">Non-grocery only</option></select><input name="limit" type="number" placeholder="Usage limit (0 = unlimited)" value="0"><label><input type="checkbox" name="active" checked> Active</label><button class="btn">Save coupon</button></form>${tbl(['Code','Type','Value','Min order','Used','Status'],c.coupons.map(x=>[x.code,x.kind,x.kind=='percent'?x.value/100+'%':money(x.value),money(x.min_order_paise),x.used+(x.usage_limit?'/'+x.usage_limit:''),x.active?pill('active'):pill('off')]))}</div>`}
 return h};

document.addEventListener('click',async e=>{const b=e.target.closest('[data-z]');if(!b)return;const z=b.dataset.z,i=b.dataset.i;try{
 if(z=='lm'){lm=i;render()}
 else if(z=='copy'){try{await navigator.clipboard.writeText(i)}catch(x){}toast('Referral link copied')}
 else if(z=='ckupd'){readCk(b.closest('form'));render()}
 else if(z=='cancel'){await api(`/orders/${i}/cancel`,{m:'POST'});toast('Order cancelled');render()}
 else if(z=='ret'){const r=prompt('Reason for return?');if(r){await api(`/orders/${i}/returns`,{m:'POST',b:{kind:'return',reason:r}});toast('Return requested')}}
 else if(z=='ofilter'){ST_F=i;render()}
 else if(z=='ost'){const s=b.dataset.s;if(['cancelled','refunded'].includes(s)&&!confirm('Are you sure? Paid orders are refunded to the customer wallet.'))return;const note=s=='shipped'?(prompt('Courier / tracking note (optional)')||''):'';await api(`/admin/orders/${i}/status`,{m:'PATCH',b:{status:s,note}});toast('Order updated');render()}
 else if(z=='ustat'){const r=prompt('Reason (recorded in the audit log)');if(!r)return;await api(`/admin/users/${i}/status`,{m:'PATCH',b:{status:b.dataset.s,reason:r}});toast('User updated');render()}
 else if(z=='uwal'){const dir=prompt('Type credit or debit');if(!['credit','debit'].includes(dir))return;const a=parseFloat(prompt('Amount in ₹'));if(!(a>0))return;const r=prompt('Reason (required)');if(!r)return;await api(`/admin/users/${i}/wallet-adjust`,{m:'POST',b:{direction:dir,amount_paise:Math.round(a*100),reason:r}});toast('Wallet adjusted')}
 else if(z=='uspon'){const sp=parseInt(prompt('New sponsor numeric user ID (e.g. 5 for USR000005). Leave empty for none.')||'',10);const r=prompt('Reason (required)');if(!r)return;await api(`/admin/users/${i}/sponsor`,{m:'POST',b:{sponsor_id:isNaN(sp)?null:sp,reason:r}});toast('Sponsor changed');render()}
 else if(z=='ret2'){const s=b.dataset.s;if(s=='refund'&&!confirm('Refund this order to the customer wallet?'))return;const note=prompt('Note (optional)')||'';await api('/admin/returns/'+i,{m:'POST',b:{action:s,note}});toast('Done');render()}
 else if(z=='pintog'){await api('/admin/pincodes/'+i,{m:'PUT',b:{fee_paise:+b.dataset.fee,active:+b.dataset.s}});render()}
 else if(z=='pimg'){const inp=document.createElement('input');inp.type='file';inp.accept='image/jpeg,image/png,image/webp';inp.onchange=async()=>{try{const fd=new FormData();fd.append('image',inp.files[0]);const r=await fetch(API+'/api/admin/products/'+i+'/image',{method:'POST',headers:{Authorization:'Bearer '+TOK},body:fd}),j=await r.json();if(!r.ok)throw new Error(j.error);await loadProducts();toast('Photo uploaded');render()}catch(x){toast(x.message)}};inp.click()}
 else if(z=='paynow'){const p=await api(`/orders/${i}/payment`);if(await payNow(p)){toast('Payment received');render()}}
 else if(z=='export'){const r=await fetch(API+'/api/admin/export/'+i,{headers:{Authorization:'Bearer '+TOK}});if(!r.ok)throw new Error('Export failed');const u=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=u;a.download='sabzomi-'+i+'.csv';a.click();URL.revokeObjectURL(u)}
 else if(z=='maint'){const r=await api('/admin/maintenance/run',{m:'POST'});toast(r.released+' released, '+r.expired+' expired');render()}
 else if(z=='flag'){await api(`/admin/risk-flags/${i}/resolve`,{m:'POST',b:{}});toast('Flag reviewed');render()}
 else if(z=='tclose'){await api(`/admin/tickets/${i}/close`,{m:'POST'});toast('Ticket closed');location.hash='me/admin'}
 else if(z=='stock'){const v=prompt('New stock quantity?');if(v===null)return;await api('/admin/products/'+i,{m:'PATCH',b:{stock:parseInt(v,10)}});await loadProducts();render()}
 else if(z=='toggle'){await api('/admin/products/'+i,{m:'PATCH',b:{active:+b.dataset.s}});await loadProducts();render()}
 else if(z=='cprev'){const d=Object.fromEntries(new FormData(b.closest('form')));const r=await api('/admin/commissions/preview',{m:'POST',b:{net_margin_paise:Math.round(d.margin*100),mlm_pool_bp:Math.round(d.pool*100),level_bp:d.levels.split(',').map(x=>Math.round(parseFloat(x)*100))}});
  $('prev').innerHTML=`<b>Commission structure preview</b><div class="sum"><span>Net margin</span><span>${money(r.net_margin_paise)}</span></div><div class="sum"><span>MLM pool</span><span>${money(r.mlm_pool_paise)}</span></div>${r.levels.map(l=>`<div class="sum"><span>${l.level==1?'Direct referrer (level 1)':'Level '+l.level} · ${l.bp/100}% of pool</span><span>${money(l.amount_paise)}</span></div>`).join('')}<div class="sum"><b>Total distributed</b><b>${money(r.distributed_paise)}</b></div><div class="sum"><span>Unallocated pool</span><span>${money(r.unallocated_pool_paise)}</span></div><div class="sum"><b>Company retained margin</b><b>${money(r.company_retained_margin_paise)}</b></div>`}
 else if(z=='release'){const r=await api('/admin/commissions/release',{m:'POST'});toast(r.released+' commissions released');render()}
 else if(false){const r=await api('/admin/commissions/release',{m:'POST'});toast(r.released+' commissions released');render()}
 else if(z=='wd'){const s=b.dataset.s,ref=s=='paid'?prompt('Payment reference (UTR)'):null;if(s=='paid'&&!ref)return;await api('/admin/withdrawals/'+i,{m:'POST',b:{status:s,reference:ref}});toast('Updated');render()}
}catch(x){toast(x.message)}});
function readCk(f){const d=Object.fromEntries(new FormData(f));Object.assign(CK,{name:d.name,phone:d.phone,line1:d.line1,pincode:d.pincode,coupon:d.coupon||'',method:d.method||'wallet'})}
async function devPay(gid){try{await api('/dev/simulate-payment',{m:'POST',b:{gateway_order_id:gid}});return true}catch(e){toast('Gateway not configured on this server');return false}}
document.addEventListener('submit',async e=>{const f=e.target.closest('[data-f]');if(!f)return;e.preventDefault();const k=f.dataset.f,d=Object.fromEntries(new FormData(f)),er=$('ferr');try{
 if(k=='login'||k=='reg'){if(k=='reg'&&!d.referral_code)delete d.referral_code;const r=await api(k=='reg'?'/auth/register':'/auth/login',{m:'POST',b:d});setAuth(r);toast('Welcome, '+r.user.name);const n=NEXT||'me/dashboard';NEXT='';location.hash=n;if(location.hash=='#'+n)render()}
 else if(k=='checkout'){readCk(f);const r=await api('/checkout',{m:'POST',b:{items:items(),address:{name:CK.name,phone:CK.phone,line1:CK.line1,pincode:CK.pincode},payment_method:CK.method,coupon:CK.coupon}});
  let paid=true;if(r.payment)paid=await payNow(r.payment);cart={};toast(paid?'Order placed: '+r.orders.length+' order(s)':'Order saved. Complete payment from My orders within 30 minutes.');location.hash='orders'}
 else if(k=='topup'){const r=await api('/wallet/topup',{m:'POST',b:{amount_paise:Math.round(d.amount*100)}});if(await payNow(r)){toast('Wallet topped up');render()}}
 else if(k=='forgot'){const r=await api('/auth/forgot',{m:'POST',b:d});toast(r.message);lm='login';render()}
 else if(k=='reset'){await api('/auth/reset',{m:'POST',b:{token:RESET,new:d.new}});history.replaceState(null,'',location.pathname);toast('Password updated. Please log in.');lm='login';location.hash='login'}
 else if(k=='usearch'){UQ=d.q||'';render()}
 else if(k=='pin'){await api('/admin/pincodes/'+d.pin,{m:'PUT',b:{fee_paise:Math.round((d.fee||0)*100),active:1}});toast('PIN code saved');render()}
 else if(k=='coupon'){const c=x=>Math.round(parseFloat(x||0)*100);await api('/admin/coupons/'+d.code.toUpperCase(),{m:'PUT',b:{kind:d.kind,value:c(d.value),min_order_paise:c(d.min),max_discount_paise:c(d.max),applies_to:d.applies,usage_limit:parseInt(d.limit||0,10),active:d.active?1:0}});toast('Coupon saved');render()}
 else if(k=='ticket'){const r=await api('/tickets',{m:'POST',b:d});toast('Ticket created');location.hash='me/ticket-'+r.id}
 else if(k=='reply'){await api(`/tickets/${f.dataset.t}/messages`,{m:'POST',b:d});toast('Reply sent');render()}
 else if(k=='profile'){await api('/me',{m:'PUT',b:d});USER.name=d.name;hdr();toast('Profile updated')}
 else if(k=='pw'){await api('/me/password',{m:'POST',b:d});f.reset();toast('Password updated')}
 else if(k=='cfg'){await api('/admin/settings',{m:'PUT',b:{mlm_pool_bp:Math.round(d.pool*100),level_bp:d.levels.split(',').map(x=>Math.round(parseFloat(x)*100)),grocery_min_paise:Math.round(d.gmin*100),free_delivery_paise:Math.round(d.free*100),grocery_fee_paise:Math.round(d.fee*100),release_days:parseInt(d.days,10)}});toast('Settings saved')}
 else if(k=='newprod'){const c=x=>Math.round(parseFloat(x||0)*100);await api('/admin/products',{m:'POST',b:{sku:d.sku,name:d.name,category:d.category,sub:d.sub,unit:d.unit,price_paise:c(d.price),mrp_paise:c(d.mrp),cost_paise:c(d.cost),other_cost_paise:c(d.other),tax_bp:c(d.tax),stock:parseInt(d.stock,10)}});await loadProducts();toast('Product added');render()}
 else if(k=='bank'){await api('/me/payout',{m:'PUT',b:{bank:{holder:d.holder,account:d.account,ifsc:d.ifsc,bank_name:d.bank_name}}});toast('Bank details saved');render()}
 else if(k=='payout'){await api('/me/payout',{m:'PUT',b:{upi:d.upi}});toast('UPI saved');render()}
 else if(k=='wd'){await api('/withdrawals',{m:'POST',b:{amount_paise:Math.round(d.amount*100),method:d.method}});toast('Withdrawal requested');render()}
}catch(x){if(er)er.textContent=x.message;else toast(x.message)}});

addEventListener('hashchange',()=>{sub='All';render();scrollTo(0,0)});boot();
